### PR TITLE
usePreparePosts undefined entries 🔴 

### PR DESCRIPTION
**Pull request by kuserich**
It appears that it's possible that by the time `usePreparePosts` is called, `query` may not have fully loaded such that `''` is passed rather than a valid array of post objects. In these instances, `find` returns `undefined` for every `id` it checks. This is because `find` returns `undefined` in case no match was found. Note that the same would happen if `id` contained an invalid or a stale reference (for instance the ID of a post that was deleted).

For simplicity and to speed things up for the first load, I have added the `isNonEmptyArray` condition for `query` as well. Speaking of this variable, would we be able to update the [default value of `query`](https://github.com/sixach/wp-react-hooks/blob/main/src/useGetPosts/index.js#L69) from an empty string to an empty array? Personally I would feel more comfortable knowing default values share the type of the intended values. Additionally, this would lift the requirements on `query` and the `isNonEmptyArray` condition could be removed. 

My proposal for `useGetPosts` is shown in #55.

This PR fixes the issue on my local in [Responsive slide (item) widths #39](https://github.com/sixach/wp-block-slider/pull/39)

### CODE REVIEW

**Review by mahdiyazdani — CHANGES_REQUESTED** [review]
Thank you @kuserich. I have initially used `find` in conjunction with the `map` method because the combination of `includes` and `filter` functions doesn’t preserve the original order of the query. 

Wouldn’t the additional conditional statement to check for a valid query be enough alone to avoid the error you are getting in the other PR?

https://user-images.githubusercontent.com/8451635/148207844-f1cc8a2e-48a2-49ac-aa5a-174d6ceb3b3b.mov

**Comment by kuserich** [comment]
> Thank you @kuserich. I have initially used find in conjunction with the map method because the combination of includes and filter functions doesn’t preserve the original order of the query. 

Ah yes, you are right. We've had this issue in the past. I totally missed that.

> Wouldn’t the additional conditional statement to check for a valid query be enough alone to avoid the error you are getting in the other PR?

Unfortunately no. If there are entries in `ids` that do not exist in `query`, the function returns `undefined` entries.

I have updated this PR with a new function and I propose to add this function in wp-block-utils and use this instead. In essence, the new function is a copy of the previous `map` + `find` approach, except that we only add existing matches (i.e. no `undefined` entries). What do you think?

**Comment by mahdiyazdani** [comment]
> Unfortunately no. If there are entries in ids that do not exist in query, the function returns undefined entries.

A slightly amended approach would filter out falsy arguments after the hook is done searching for the given post ids:

```js
const { havePosts, maxLimit, slicedQuery } = useMemo(
	() => ( {
		havePosts: isNonEmptyArray( query ),
		maxLimit: query?.length,
		slicedQuery: isNonEmptyArray( ids )
			? pickBy(
					map( ids, ( id ) => find( query, [ 'id', id ] ) ),
					( post ) => identity( post )
			  )
			: slice( query, 0, limit ),
	} ),
	[ ids, limit, query ]
);
```

I have prepared a small [live demo](https://codesandbox.io/s/useprepareposts-2yvqv?file=/src/index.js) to play with this approach around. What do you think?

**Comment by kuserich** [comment]
> > Unfortunately no. If there are entries in ids that do not exist in query, the function returns undefined entries.
> 
> A slightly amended approach would filter out falsy arguments after the hook is done searching for the given post ids:
> 
> ```js
> const { havePosts, maxLimit, slicedQuery } = useMemo(
> 	() => ( {
> 		havePosts: isNonEmptyArray( query ),
> 		maxLimit: query?.length,
> 		slicedQuery: isNonEmptyArray( ids )
> 			? pickBy(
> 					map( ids, ( id ) => find( query, [ 'id', id ] ) ),
> 					( post ) => identity( post )
> 			  )
> 			: slice( query, 0, limit ),
> 	} ),
> 	[ ids, limit, query ]
> );
> ```
> 
> I have prepared a small [live demo](https://codesandbox.io/s/useprepareposts-2yvqv?file=/src/index.js) to play with this approach around. What do you think?

Thank you, @mahdiyazdani . I've been thinking about a similar solution where the result of `map` + `find` could be filtered. The main disadvantage of this approach is that we iterate over the entire result set again, which could be the entire `query` array if all posts are selected.

Although I do find this approach more elegant, I would be in favour of a separate function that minimizes the number of iterations. What do you think?

**Comment by mahdiyazdani** [comment]
> Although I do find this approach more elegant, I would be in favour of a separate function that minimizes the number of iterations. What do you think?

Absolutely. We can essentially reuse the new function in several instances that we currently need/have 🙂

**Comment by kuserich** [comment]
Thank you, @mahdiyazdani . I have replaced the demo function with the newly introduced `filterCollectionByValues`.

**Review by mahdiyazdani — APPROVED** [review]
Thank you @kuserich 👍

**Pull request merged**
